apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: calculatrice-api-claim0
  name: calculatrice-api-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storagePVC }}