name: calculatrice CICD

on:
  push:
    branches:
      - develop
    tags: 
      - 'v*.*.*'
  workflow_dispatch:
    # Permet le déclenchement manuel
    inputs:
      deploy:
        description: 'Deploy manually'
        required: false

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        
      - name: Build
        run: go build -v ./...
  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        
      - name: Test
        run: go test -v ./...

  build_push_dev_image:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Development Docker image
        run: docker build -t calculatrice-api:dev .
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Development Docker image
        run: |
          docker tag calculatrice-api:dev ycostarddev/calculatrice-api:dev
          docker push ycostarddev/calculatrice-api:dev

  build_push_prod_image:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Prod Docker image
        run: docker build -t calculatrice-api:${{ github.ref_name }} .
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Prod Docker image
        run: |
          docker tag calculatrice-api:${{ github.ref_name }} ycostarddev/calculatrice-api:${{ github.ref_name }}
          docker push ycostarddev/calculatrice-api:${{ github.ref_name }}

  deploy:
    runs-on: ubuntu-latest
    needs: build_push_prod_image
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref_type == 'tag' && github.event.inputs.deploy)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deployment step (manual)
        run: echo "Deploying to server..."